server:
    port: 10081
spring:
    profiles:
        active: dev 
        
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        validation-query: SELECT 1
        test-on-borrow: true
        test-on-return: true
    freemarker:
        suffix: .html
    jackson:
        serialization:
            indent_output: true
jfish: 
    autoConfig: web-ms
    mvc: 
        mediaType:
            json: application/json
            xls: application/vnd.ms-excel
            xml: application/xml

webchat: 
    token: GHIOP34asdF5678JKertyU
    appid: wxfd97aa55109ff0bf
    appsecret: 50f2d9b3439314424fe3114c5f4db42c
    at: _SkUsXcsz2PA9KS5ACyx1YekcufU7uK-HxJPlqkuw0sf2LguxsMKmX1hj4q8qDYGDDZpenRm0LQBtTOELMHKAF9zM_8nWxpqnRCmx8AGw51vBh3QN6TeqPzvZMV1ZPA0XAJdAHAEHQ
